### ISSUE TITLE
Question on correct branch

### ISSUE THREAD

**Issue by smit1678** [ReliefApplications/hot-dashboard#2]
@arturopignon @AlexisReliefApps Which branch is the correct/most up to date branch? It looks like `devarchitecture` is the most up to date but `dev` and `master` are not in sync.

**Comment by Reliefapps** [comment]
Hi Nate,

The latest release v1.0.1 was made from devarchitetcure: 
https://github.com/ReliefApplications/hot-dashboard/releases

Let me merge all branches so it is clearer (I'll put everything on Dev 
and synch Master as well).

I will let you know as as as it is done

Best regards

Raphael



RAPHAEL BONNAUD
CEO
http://reliefapps.org <http://reliefapps.org>

Mobile TH. +66 652160260
Mobile FR. +33 (0) 695397797
Skype. raphael.bonnaud

**Comment by smit1678** [comment]
Great, thank you for doing that.

Nate Smith
@nas_smith

________________________________

**Comment by Reliefapps** [comment]
All done. Now Dev is the latest branch (and it is synched with master).

Master is protected

Dev is the default

I made a new tag v1.0.2 (synched with Dev and Master).

So all cleaned and ready

Cheers

Raphael


RAPHAEL BONNAUD
CEO
http://reliefapps.org <http://reliefapps.org>

Mobile TH. +66 652160260
Mobile FR. +33 (0) 695397797
Skype. raphael.bonnaud

**Comment by smit1678** [comment]
👍 thanks. I scratched our initial fork since there were major conflicts and started over. Tracking everything over there now: https://github.com/hotosm/hot-dashboard.
